# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build the docker-compose stack
      run: cd tests && docker compose up django -d && cd ..

    - name: Check running containers
      run: docker ps
    
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.5"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run the program against Django
      run: tests/run.sh
      
    - name: Analyze results
      run: tests/report.sh
